package knowledge

import (
	"regexp"
	"strings"

	"aspm/internal/ai"
	"aspm/internal/models"
	"aspm/internal/repository"
)

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func Slugify(value string) string {
	value = strings.ToLower(value)
	value = nonAlnum.ReplaceAllString(value, "-")
	value = strings.Trim(value, "-")
	return value
}

func BuildCreateArticle(title, contentMD string, tags, cweIDs, ruleIDs []string, scanner string) repository.ArticleCreate {
	return repository.ArticleCreate{
		Slug:      Slugify(title),
		Title:     title,
		ContentMD: contentMD,
		Tags:      nilToEmpty(tags),
		CWEIDs:    nilToEmpty(cweIDs),
		RuleIDs:   nilToEmpty(ruleIDs),
		Scanner:   scanner,
	}
}

func BuildRemediationRequest(src *repository.RemediationSource) ai.RemediationRequest {
	return ai.RemediationRequest{
		RuleID:      src.RuleID,
		Title:       src.Title,
		Description: src.Description,
		Severity:    src.Severity,
		Scanner:     src.Scanner,
		FilePath:    src.FilePath,
		CodeSnippet: src.CodeSnippet,
		CVEID:       src.CVEID,
		CWEID:       src.CWEID,
	}
}

func BuildGeneratedArticle(src *repository.RemediationSource, content string) repository.ArticleCreate {
	slug := "ai-" + Slugify(src.RuleID+"-"+src.Title)
	if len(slug) > 80 {
		slug = slug[:80]
	}

	tags := []string{"ai-generated", src.Scanner}
	cweIDs := []string{}
	if src.CWEID != "" {
		cweIDs = append(cweIDs, src.CWEID)
	}

	return repository.ArticleCreate{
		Slug:          slug,
		Title:         src.Title,
		ContentMD:     content,
		Tags:          tags,
		CWEIDs:        cweIDs,
		RuleIDs:       []string{src.RuleID},
		Scanner:       src.Scanner,
		AutoGenerated: true,
	}
}

func BuildGeneratedArticleFallback(article repository.ArticleCreate) models.Article {
	return models.Article{
		Slug:          article.Slug,
		Title:         article.Title,
		ContentMD:     article.ContentMD,
		Tags:          article.Tags,
		CWEIDs:        article.CWEIDs,
		RuleIDs:       article.RuleIDs,
		Scanner:       article.Scanner,
		AutoGenerated: article.AutoGenerated,
	}
}

func nilToEmpty(values []string) []string {
	if values == nil {
		return []string{}
	}
	return values
}
