package knowledge

import (
	"testing"

	"aspm/internal/assert"
	"aspm/internal/repository"
)

func TestSlugify(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"basic", "Hello World", "hello-world"},
		{"special chars", "API Security Guide!", "api-security-guide"},
		{"multiple dashes", "foo---bar", "foo-bar"},
		{"trailing dash", "hello-", "hello"},
		{"leading dash", "-hello", "hello"},
		{"unicode", "Security à la carte", "security-la-carte"},
		{"empty", "", ""},
		{"already slug", "hello-world", "hello-world"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, Slugify(tt.input))
		})
	}
}

func TestBuildCreateArticle(t *testing.T) {
	article := BuildCreateArticle("Test Article", "# Content", []string{"tag1"}, []string{"CWE-79"}, []string{"semgrep-rule-1"}, "semgrep")

	assert.Equal(t, "test-article", article.Slug)
	assert.Equal(t, "Test Article", article.Title)
	assert.Equal(t, "# Content", article.ContentMD)
	assert.Equal(t, []string{"tag1"}, article.Tags)
	assert.Equal(t, []string{"CWE-79"}, article.CWEIDs)
	assert.Equal(t, []string{"semgrep-rule-1"}, article.RuleIDs)
	assert.Equal(t, "semgrep", article.Scanner)
}

func TestBuildCreateArticle_NilTags(t *testing.T) {
	article := BuildCreateArticle("Title", "content", nil, nil, nil, "grype")
	assert.Equal(t, []string{}, article.Tags)
	assert.Equal(t, []string{}, article.CWEIDs)
	assert.Equal(t, []string{}, article.RuleIDs)
}

func TestBuildRemediationRequest(t *testing.T) {
	src := &repository.RemediationSource{
		RuleID:      "CVE-2024-21626",
		Title:       "runc breakout",
		Description: "runc file descriptor leak",
		Severity:    "critical",
		Scanner:     "grype",
		FilePath:    "/go.sum",
		CodeSnippet: "runc v1.1.11",
		CVEID:       "CVE-2024-21626",
		CWEID:       "CWE-403",
	}
	result := BuildRemediationRequest(src)

	assert.Equal(t, src.RuleID, result.RuleID)
	assert.Equal(t, src.Title, result.Title)
	assert.Equal(t, src.Description, result.Description)
	assert.Equal(t, src.Severity, result.Severity)
	assert.Equal(t, src.CVEID, result.CVEID)
	assert.Equal(t, src.CWEID, result.CWEID)
	assert.Equal(t, src.FilePath, result.FilePath)
	assert.Equal(t, src.CodeSnippet, result.CodeSnippet)
}

func TestBuildGeneratedArticle(t *testing.T) {
	src := &repository.RemediationSource{
		RuleID: "CVE-2024-21626",
		Title:  "runc breakout",
		Scanner: "grype",
		CWEID:  "CWE-403",
	}
	article := BuildGeneratedArticle(src, "## Remediation\nUpdate runc to v1.1.12")

	assert.Equal(t, "ai-cve-2024-21626-runc-breakout", article.Slug)
	assert.Equal(t, src.Title, article.Title)
	assert.Equal(t, "## Remediation\nUpdate runc to v1.1.12", article.ContentMD)
	assert.Equal(t, []string{"ai-generated"}, article.Tags)
	assert.Equal(t, []string{"CWE-403"}, article.CWEIDs)
	assert.Equal(t, []string{"CVE-2024-21626"}, article.RuleIDs)
	assert.Equal(t, "grype", article.Scanner)
	assert.True(t, article.AutoGenerated)
}

func TestBuildGeneratedArticle_LongSlug(t *testing.T) {
	src := &repository.RemediationSource{
		RuleID: "very-long-rule-id-that-exceeds-eighty-characters-when-combined",
		Title:  "extremely long title that will definitely exceed the 80 character slug limit by a lot",
		Scanner: "checkov",
	}
	article := BuildGeneratedArticle(src, "content")
	assert.True(t, len(article.Slug) <= 80)
}

func TestBuildGeneratedArticle_NoCWE(t *testing.T) {
	src := &repository.RemediationSource{
		RuleID: "R123",
		Title:  "Finding",
		Scanner: "semgrep",
	}
	article := BuildGeneratedArticle(src, "content")
	assert.Equal(t, []string{}, article.CWEIDs) // no CWEID → empty slice
}

func TestBuildGeneratedArticleFallback(t *testing.T) {
	ac := repository.ArticleCreate{
		Slug:          "test-slug",
		Title:         "Test Title",
		ContentMD:     "# Content",
		Tags:          []string{"tag1"},
		CWEIDs:        []string{"CWE-79"},
		RuleIDs:       []string{"rule1"},
		Scanner:       "semgrep",
		AutoGenerated: true,
	}
	article := BuildGeneratedArticleFallback(ac)
	assert.Equal(t, ac.Slug, article.Slug)
	assert.Equal(t, ac.Title, article.Title)
	assert.Equal(t, ac.ContentMD, article.ContentMD)
	assert.Equal(t, ac.Tags, article.Tags)
	assert.Equal(t, ac.CWEIDs, article.CWEIDs)
	assert.Equal(t, ac.RuleIDs, article.RuleIDs)
	assert.Equal(t, ac.AutoGenerated, article.AutoGenerated)
}

func TestNilToEmpty(t *testing.T) {
	assert.Equal(t, []string{}, nilToEmpty(nil))
	assert.Equal(t, []string{}, nilToEmpty([]string{}))
	assert.Equal(t, []string{"a"}, nilToEmpty([]string{"a"}))
}
