package repository

import (
	"context"
	"fmt"

	"aspm/internal/models"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type knowledgeRepo struct{ db *pgxpool.Pool }

const articleCols = `id, slug, title, content_md, tags, cwe_ids, rule_ids, scanner, auto_generated, created_at, updated_at`

func scanArticle(row interface {
	Scan(dest ...any) error
}) (*models.Article, error) {
	var a models.Article
	err := row.Scan(&a.ID, &a.Slug, &a.Title, &a.ContentMD,
		&a.Tags, &a.CWEIDs, &a.RuleIDs, &a.Scanner,
		&a.AutoGenerated, &a.CreatedAt, &a.UpdatedAt)
	if err != nil {
		return nil, err
	}
	return &a, nil
}

func (r *knowledgeRepo) List(ctx context.Context, f KnowledgeFilter) ([]models.Article, error) {
	rows, err := r.db.Query(ctx, `
		SELECT `+articleCols+`
		FROM knowledge_articles
		WHERE ($1 = '' OR title ILIKE '%'||$1||'%' OR content_md ILIKE '%'||$1||'%')
		  AND ($2 = '' OR scanner = $2)
		  AND ($3 = '' OR $3 = ANY(tags))
		  AND ($4 = '' OR $4 = ANY(cwe_ids))
		  AND ($5 = '' OR $5 = ANY(rule_ids))
		ORDER BY auto_generated ASC, updated_at DESC`,
		f.Search, f.Scanner, f.Tag, f.CWEID, f.RuleID)
	if err != nil {
		return nil, fmt.Errorf("knowledge list: %w", err)
	}
	defer rows.Close()

	articles := []models.Article{}
	for rows.Next() {
		a, err := scanArticle(rows)
		if err != nil {
			continue
		}
		articles = append(articles, *a)
	}
	return articles, nil
}

func (r *knowledgeRepo) GetBySlug(ctx context.Context, slug string) (*models.Article, error) {
	row := r.db.QueryRow(ctx,
		`SELECT `+articleCols+` FROM knowledge_articles WHERE slug = $1`, slug)
	a, err := scanArticle(row)
	if err != nil {
		return nil, err
	}
	return a, nil
}

func (r *knowledgeRepo) Create(ctx context.Context, ac ArticleCreate) (*models.Article, error) {
	row := r.db.QueryRow(ctx, `
		INSERT INTO knowledge_articles (slug, title, content_md, tags, cwe_ids, rule_ids, scanner)
		VALUES ($1,$2,$3,$4,$5,$6,$7)
		RETURNING `+articleCols,
		ac.Slug, ac.Title, ac.ContentMD, ac.Tags, ac.CWEIDs, ac.RuleIDs, ac.Scanner)
	a, err := scanArticle(row)
	if err != nil {
		return nil, fmt.Errorf("create article: %w", err)
	}
	return a, nil
}

func (r *knowledgeRepo) Upsert(ctx context.Context, ac ArticleCreate) (*models.Article, error) {
	row := r.db.QueryRow(ctx, `
		INSERT INTO knowledge_articles (slug, title, content_md, tags, cwe_ids, rule_ids, scanner, auto_generated)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
		ON CONFLICT (slug) DO UPDATE SET content_md=EXCLUDED.content_md, updated_at=NOW()
		RETURNING `+articleCols,
		ac.Slug, ac.Title, ac.ContentMD, ac.Tags, ac.CWEIDs, ac.RuleIDs, ac.Scanner, ac.AutoGenerated)
	a, err := scanArticle(row)
	if err != nil {
		return nil, fmt.Errorf("upsert article: %w", err)
	}
	return a, nil
}

func (r *knowledgeRepo) Update(ctx context.Context, slug string, upd ArticleUpdate) error {
	_, err := r.db.Exec(ctx, `
		UPDATE knowledge_articles SET
			title      = COALESCE($2, title),
			content_md = COALESCE($3, content_md),
			tags       = COALESCE($4, tags),
			cwe_ids    = COALESCE($5, cwe_ids),
			rule_ids   = COALESCE($6, rule_ids),
			scanner    = COALESCE($7, scanner),
			auto_generated = FALSE,
			updated_at = NOW()
		WHERE slug = $1`,
		slug, upd.Title, upd.ContentMD, upd.Tags, upd.CWEIDs, upd.RuleIDs, upd.Scanner)
	return err
}

func (r *knowledgeRepo) Delete(ctx context.Context, slug string) error {
	_, err := r.db.Exec(ctx, `DELETE FROM knowledge_articles WHERE slug = $1`, slug)
	return err
}

func (r *knowledgeRepo) FindByRuleID(ctx context.Context, ruleID string) (*models.Article, error) {
	row := r.db.QueryRow(ctx,
		`SELECT `+articleCols+` FROM knowledge_articles WHERE $1 = ANY(rule_ids) LIMIT 1`, ruleID)
	a, err := scanArticle(row)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return a, nil
}

func (r *knowledgeRepo) FindByCWEOrRule(ctx context.Context, cweID, ruleID string) (*models.Article, error) {
	row := r.db.QueryRow(ctx, `
		SELECT `+articleCols+`
		FROM knowledge_articles
		WHERE ($1 = '' OR $1 = ANY(rule_ids))
		   OR ($2 = '' OR $2 = ANY(cwe_ids))
		ORDER BY auto_generated ASC
		LIMIT 1`, ruleID, cweID)
	a, err := scanArticle(row)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return a, nil
}
