package repository

import (
	"context"
	"fmt"

	"aspm/internal/models"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type knowledgeRepo struct{ db *pgxpool.Pool }

const articleCols = `id, slug, title, content_md, tags, cwe_ids, rule_ids, scanner, auto_generated, created_at, updated_at`

func scanArticle(row interface {
	Scan(dest ...any) error
}) (*models.Article, error) {
	var a models.Article
	err := row.Scan(&a.ID, &a.Slug, &a.Title, &a.ContentMD,
		&a.Tags, &a.CWEIDs, &a.RuleIDs, &a.Scanner,
		&a.AutoGenerated, &a.CreatedAt, &a.UpdatedAt)
	if err != nil {
		return nil, err
	}
	return &a, nil
}

func (r *knowledgeRepo) List(ctx context.Context, f KnowledgeFilter) ([]models.Article, error) {
	rows, err := r.db.Query(ctx, `
		SELECT `+articleCols+`
		FROM knowledge_articles
		WHERE (@search = '' OR title ILIKE '%'||@search||'%' OR content_md ILIKE '%'||@search||'%')
		  AND (@scanner = '' OR scanner = @scanner)
		  AND (@tag = '' OR @tag = ANY(tags))
		  AND (@cwe_id = '' OR @cwe_id = ANY(cwe_ids))
		  AND (@rule_id = '' OR @rule_id = ANY(rule_ids))
		ORDER BY auto_generated ASC, updated_at DESC`,
		pgx.NamedArgs{
			"search":   f.Search,
			"scanner":  f.Scanner,
			"tag":      f.Tag,
			"cwe_id":  f.CWEID,
			"rule_id": f.RuleID,
		})
	if err != nil {
		return nil, fmt.Errorf("knowledge list: %w", err)
	}
	defer rows.Close()

	articles := []models.Article{}
	for rows.Next() {
		a, err := scanArticle(rows)
		if err != nil {
			continue
		}
		articles = append(articles, *a)
	}
	return articles, nil
}

func (r *knowledgeRepo) GetBySlug(ctx context.Context, slug string) (*models.Article, error) {
	row := r.db.QueryRow(ctx,
		`SELECT `+articleCols+` FROM knowledge_articles WHERE slug = $1`, slug)
	a, err := scanArticle(row)
	if err != nil {
		return nil, err
	}
	return a, nil
}

func (r *knowledgeRepo) Create(ctx context.Context, ac ArticleCreate) (*models.Article, error) {
	row := r.db.QueryRow(ctx, `
		INSERT INTO knowledge_articles (slug, title, content_md, tags, cwe_ids, rule_ids, scanner)
		VALUES (@slug, @title, @content_md, @tags, @cwe_ids, @rule_ids, @scanner)
		RETURNING `+articleCols,
		pgx.NamedArgs{
			"slug":       ac.Slug,
			"title":      ac.Title,
			"content_md": ac.ContentMD,
			"tags":       ac.Tags,
			"cwe_ids":   ac.CWEIDs,
			"rule_ids":  ac.RuleIDs,
			"scanner":   ac.Scanner,
		})
	a, err := scanArticle(row)
	if err != nil {
		return nil, fmt.Errorf("create article: %w", err)
	}
	return a, nil
}

func (r *knowledgeRepo) Upsert(ctx context.Context, ac ArticleCreate) (*models.Article, error) {
	row := r.db.QueryRow(ctx, `
		INSERT INTO knowledge_articles (slug, title, content_md, tags, cwe_ids, rule_ids, scanner, auto_generated)
		VALUES (@slug, @title, @content_md, @tags, @cwe_ids, @rule_ids, @scanner, @auto_generated)
		ON CONFLICT (slug) DO UPDATE SET content_md=EXCLUDED.content_md, updated_at=NOW()
		RETURNING `+articleCols,
		pgx.NamedArgs{
			"slug":           ac.Slug,
			"title":         ac.Title,
			"content_md":     ac.ContentMD,
			"tags":           ac.Tags,
			"cwe_ids":       ac.CWEIDs,
			"rule_ids":      ac.RuleIDs,
			"scanner":       ac.Scanner,
			"auto_generated": ac.AutoGenerated,
		})
	a, err := scanArticle(row)
	if err != nil {
		return nil, fmt.Errorf("upsert article: %w", err)
	}
	return a, nil
}

func (r *knowledgeRepo) Update(ctx context.Context, slug string, upd ArticleUpdate) error {
	_, err := r.db.Exec(ctx, `
		UPDATE knowledge_articles SET
			title      = COALESCE(@title, title),
			content_md = COALESCE(@content_md, content_md),
			tags       = COALESCE(@tags, tags),
			cwe_ids    = COALESCE(@cwe_ids, cwe_ids),
			rule_ids   = COALESCE(@rule_ids, rule_ids),
			scanner    = COALESCE(@scanner, scanner),
			auto_generated = FALSE,
			updated_at = NOW()
		WHERE slug = @slug`,
		pgx.NamedArgs{
			"slug":       slug,
			"title":      upd.Title,
			"content_md": upd.ContentMD,
			"tags":       upd.Tags,
			"cwe_ids":   upd.CWEIDs,
			"rule_ids":  upd.RuleIDs,
			"scanner":   upd.Scanner,
		})
	return err
}

func (r *knowledgeRepo) Delete(ctx context.Context, slug string) error {
	_, err := r.db.Exec(ctx, `DELETE FROM knowledge_articles WHERE slug = $1`, slug)
	return err
}

func (r *knowledgeRepo) FindByRuleID(ctx context.Context, ruleID string) (*models.Article, error) {
	row := r.db.QueryRow(ctx,
		`SELECT `+articleCols+` FROM knowledge_articles WHERE $1 = ANY(rule_ids) LIMIT 1`, ruleID)
	a, err := scanArticle(row)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return a, nil
}

func (r *knowledgeRepo) FindByCWEOrRule(ctx context.Context, cweID, ruleID string) (*models.Article, error) {
	row := r.db.QueryRow(ctx, `
		SELECT `+articleCols+`
		FROM knowledge_articles
		WHERE (@rule_id = '' OR @rule_id = ANY(rule_ids))
		   OR (@cwe_id = '' OR @cwe_id = ANY(cwe_ids))
		ORDER BY auto_generated ASC
		LIMIT 1`,
		pgx.NamedArgs{
			"rule_id": ruleID,
			"cwe_id":  cweID,
		})
	a, err := scanArticle(row)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return a, nil
}
