package handlers

import (
	"encoding/json"
	"net/http"
	"regexp"
	"strings"

	"aspm/internal/ai"
	"aspm/internal/models"
	"aspm/internal/repository"

	"github.com/go-chi/chi/v5"
)

func (h *Handler) ListArticles(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	articles, err := h.store.Knowledge.List(r.Context(), repository.KnowledgeFilter{
		Search:  q.Get("q"),
		Scanner: q.Get("scanner"),
		Tag:     q.Get("tag"),
		CWEID:   q.Get("cwe_id"),
		RuleID:  q.Get("rule_id"),
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to list articles")
		return
	}
	writeJSON(w, http.StatusOK, articles)
}

func (h *Handler) GetArticle(w http.ResponseWriter, r *http.Request) {
	a, err := h.store.Knowledge.GetBySlug(r.Context(), chi.URLParam(r, "slug"))
	if err != nil {
		writeError(w, http.StatusNotFound, "article not found")
		return
	}
	writeJSON(w, http.StatusOK, a)
}

func (h *Handler) CreateArticle(w http.ResponseWriter, r *http.Request) {
	var body struct {
		Title     string   `json:"title"`
		ContentMD string   `json:"content_md"`
		Tags      []string `json:"tags"`
		CWEIDs    []string `json:"cwe_ids"`
		RuleIDs   []string `json:"rule_ids"`
		Scanner   string   `json:"scanner"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil || body.Title == "" {
		writeError(w, http.StatusBadRequest, "title required")
		return
	}
	if body.Tags == nil {
		body.Tags = []string{}
	}
	if body.CWEIDs == nil {
		body.CWEIDs = []string{}
	}
	if body.RuleIDs == nil {
		body.RuleIDs = []string{}
	}

	a, err := h.store.Knowledge.Create(r.Context(), repository.ArticleCreate{
		Slug: slugify(body.Title), Title: body.Title, ContentMD: body.ContentMD,
		Tags: body.Tags, CWEIDs: body.CWEIDs, RuleIDs: body.RuleIDs, Scanner: body.Scanner,
	})
	if err != nil {
		writeError(w, http.StatusConflict, "slug already exists or DB error: "+err.Error())
		return
	}
	writeJSON(w, http.StatusCreated, a)
}

func (h *Handler) UpdateArticle(w http.ResponseWriter, r *http.Request) {
	slug := chi.URLParam(r, "slug")
	var body struct {
		Title     *string  `json:"title"`
		ContentMD *string  `json:"content_md"`
		Tags      []string `json:"tags"`
		CWEIDs    []string `json:"cwe_ids"`
		RuleIDs   []string `json:"rule_ids"`
		Scanner   *string  `json:"scanner"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		writeError(w, http.StatusBadRequest, "invalid body")
		return
	}
	if err := h.store.Knowledge.Update(r.Context(), slug, repository.ArticleUpdate{
		Title: body.Title, ContentMD: body.ContentMD,
		Tags: body.Tags, CWEIDs: body.CWEIDs, RuleIDs: body.RuleIDs, Scanner: body.Scanner,
	}); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to update article")
		return
	}
	h.GetArticle(w, r)
}

func (h *Handler) DeleteArticle(w http.ResponseWriter, r *http.Request) {
	h.store.Knowledge.Delete(r.Context(), chi.URLParam(r, "slug"))
	w.WriteHeader(http.StatusNoContent)
}

func (h *Handler) AIRemediate(w http.ResponseWriter, r *http.Request) {
	var body struct {
		FindingID string `json:"finding_id"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil || body.FindingID == "" {
		writeError(w, http.StatusBadRequest, "finding_id required")
		return
	}

	src, err := h.store.Findings.GetForRemediation(r.Context(), body.FindingID)
	if err != nil {
		writeError(w, http.StatusNotFound, "finding not found")
		return
	}

	// Check cache first
	if cached, _ := h.store.Knowledge.FindByRuleID(r.Context(), src.RuleID); cached != nil {
		h.store.Findings.UpdateRemediationSlug(r.Context(), body.FindingID, cached.Slug)
		writeJSON(w, http.StatusOK, map[string]any{"article": cached, "cached": true})
		return
	}

	content, err := ai.GenerateRemediation(r.Context(), ai.RemediationRequest{
		RuleID: src.RuleID, Title: src.Title, Description: src.Description,
		Severity: src.Severity, Scanner: src.Scanner, FilePath: src.FilePath,
		CodeSnippet: src.CodeSnippet, CVEID: src.CVEID, CWEID: src.CWEID,
	})
	if err != nil {
		writeError(w, http.StatusServiceUnavailable, "AI generation failed: "+err.Error())
		return
	}

	slug := "ai-" + slugify(src.RuleID+"-"+src.Title)
	if len(slug) > 80 {
		slug = slug[:80]
	}

	tags := []string{"ai-generated", src.Scanner}
	cwes := []string{}
	if src.CWEID != "" {
		cwes = append(cwes, src.CWEID)
	}

	a, err := h.store.Knowledge.Upsert(r.Context(), repository.ArticleCreate{
		Slug: slug, Title: src.Title, ContentMD: content,
		Tags: tags, CWEIDs: cwes, RuleIDs: []string{src.RuleID},
		Scanner: src.Scanner, AutoGenerated: true,
	})
	if err != nil {
		writeJSON(w, http.StatusOK, map[string]any{
			"article": models.Article{
				Slug: slug, Title: src.Title, ContentMD: content,
				Tags: tags, CWEIDs: cwes, RuleIDs: []string{src.RuleID},
				Scanner: src.Scanner, AutoGenerated: true,
			},
			"cached": false,
		})
		return
	}

	h.store.Findings.UpdateRemediationSlug(r.Context(), body.FindingID, a.Slug)
	writeJSON(w, http.StatusOK, map[string]any{"article": a, "cached": false})
}

func (h *Handler) FindArticleForFinding(w http.ResponseWriter, r *http.Request) {
	ruleID := r.URL.Query().Get("rule_id")
	cweID := r.URL.Query().Get("cwe_id")
	if ruleID == "" && cweID == "" {
		writeError(w, http.StatusBadRequest, "rule_id or cwe_id required")
		return
	}

	a, err := h.store.Knowledge.FindByCWEOrRule(r.Context(), cweID, ruleID)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "lookup failed")
		return
	}
	if a == nil {
		writeJSON(w, http.StatusOK, map[string]any{"found": false})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"found": true, "article": a})
}

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func slugify(s string) string {
	s = strings.ToLower(s)
	s = nonAlnum.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	return s
}
